### ISSUE TITLE
address not showing up on map

### ISSUE THREAD

**Issue by lizbittner** [lonsun/richmond_trees-admin#13]
one address that did not show up on the database map, and I notice on google maps you can't get a street view: 968 34th.

**Comment by lonsun** [comment]
It looks like that address doesn't exist. I looked on street view and it jumps from 962 to 970.  Checkout:

https://www.google.com/maps/@37.9463711,-122.3345837,3a,75y,77.85h,58.99t/data=!3m6!1e1!3m4!1s4XNyzDhhmu0Evn4P1uBL6g!2e0!7i13312!8i6656

There is a tree at 962 34th that's not in the db.  It looks like it might be a RT tree.  Can't correlate the tree type because the existing 968 entry's tree is "unknown".  I'm closing this as it is a data issue, but let me know if you need anything else on it.

**Comment by lizbittner** [comment]
thanks!
