### ISSUE TITLE
2 trees to delete

### ISSUE THREAD

**Issue by lizbittner** [lonsun/richmond_trees-admin#28]
Lon - I have been working on cleaning up the tree list, and filling in missing information.  2 trees on the list are duplicates: Flowering Plum and Strawberry Tree.  I thought I had made edits to all records that contain these names, so that there does not appear to be records with these tree names.  But I am not being allowed to delete them. (I was not able to find records for the 2nd Strawberry Tree listed.)

**Comment by lonsun** [comment]
Hi Liz,

It looks like the flowering plum is still tied to an adoption request (which is there because give them the option to choose a tree to plant).  The adoption request is for 3218 Roosevelt.  If you change the tree on that request then you'll be able to delete the tree.

Both of the strawberry trees had multiple planting records tied to them.  Since they were exact duplicates, I assigned all plantings and adoption requests to one of them and deleted the other. So this part should be good to go.

**Comment by lizbittner** [comment]
Perfect, thanks!
